version: '3.7' 
services:
  master: #自定义服务名
    image: redis:5.0.7
    restart: always
    container_name: redis-master
    command: redis-server --port 16380 --requirepass 123456 --protected-mode no --daemonize no #容器启动后，运行的命令
    ports:
      - 16380:16380 #宿主机的16380映射容器内部的16380端口
    networks:
      - redis-net
  slave1:
    image: redis:5.0.7
    restart: always
    container_name: redis-slave-1
    command: redis-server --slaveof 192.168.226.20 16380 --port 16381 --requirepass 123456 --masterauth 123456 --protected-mode no --daemonize no
    ports:
    - 16381:16381
    networks:
      - redis-net
  slave2:
    image: redis:5.0.7
    restart: always
    container_name: redis-slave-2
    command: redis-server --slaveof 192.168.226.20 16380 --port 16382 --requirepass 123456 --masterauth 123456 --protected-mode no --daemonize no
    ports:
    - 16382:16382
    networks:
      - redis-net
      
networks:
  redis-net:
    name: redis-net
