version: '2.2'
services:
  kibana:
    image: 192.168.136.143:5000/kibana:7.5.0
    container_name: kibana73
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
      - elasticsearch.url="http://es73:9200"
    ports:
      - "5601:5601"
    networks:
      - es73net
  elasticsearch:
    image: 192.168.136.143:5000/elasticsearch:7.5.0
    container_name: es73
    environment:
      - cluster.name=my-elastic
      - node.name=es73
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es73
      - cluster.initial_master_nodes=es73
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es73data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es73net

volumes:
  es73data1:
    driver: local

networks:
  es73net:
    driver: bridge
