version: '3.3'
services:
  kibana:
    image: 192.168.136.143:5000/kibana:7.5.0
    container_name: 'kibana75'
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED=true
#    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - 5601:5601
    networks:
      - es7net
