version: '3.1'

services:
  zookeeper:
    image: 192.168.136.143:5000/zookeeper:3.5.6
    container_name: zookeeper
    restart: always

  nimbus:
    image: storm:2.1.0
    #container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
    #  - 6627:6627
      - 6627

  supervisor:
    image: storm:2.1.0
    #container_name: supervisor
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    restart: always

  storm-ui:
    image: storm:2.1.0
    container_name: storm-ui
    command: storm ui
    depends_on:
      - nimbus
      - zookeeper
      - supervisor
    links:
      - nimbus
      - zookeeper
      - supervisor
    restart: always
    ports:
      - 8080:8080
