version: '3.4'

services:
  zoo1:
    image: 192.168.136.143:5000/zookeeper:3.5.6
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
    - 2184:2181
    volumes:
    - "/data/zk/zoo1/data:/data"
    - "/data/zk/zoo1/datalog:/datalog"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      br17219:
        ipv4_address: 172.19.0.11

  zoo2:
    image: 192.168.136.143:5000/zookeeper:3.5.6
    restart: always
    hostname: zoo2
    container_name: zoo2
    ports:
    - 2185:2181
    volumes:
    - "/data/zk/zoo2/data:/data"
    - "/data/zk/zoo2/datalog:/datalog"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      br17219:
        ipv4_address: 172.19.0.12

  zoo3:
    image: 192.168.136.143:5000/zookeeper:3.5.6
    restart: always
    hostname: zoo3
    container_name: zoo3
    ports:
    - 2186:2181
    volumes:
    - "/data/zk/zoo3/data:/data"
    - "/data/zk/zoo3/datalog:/datalog"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      br17219:
        ipv4_address: 172.19.0.13

networks:
  br17219:
    external:
      name: br17219