version: "2"

services:
  master:
    image: singularities/spark:2.0
    command: start-spark master
    hostname: master
    ports:
      - "6066:6066"
      - "7070:7070"
      - "8080:8080"
      - "50070:50070"
    restart: always

  worker:
    image: singularities/spark:2.0
    command: start-spark worker master
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    depends_on:
      - master
    links:
      - master
    restart: always
