version: "3.9"
x-logging:
  &norm-logging
  driver: loki
  options:
    loki-url: "http://192.168.226.20:3100/loki/api/v1/push"
    max-size: "50m"
    max-file: "10"
    loki-pipeline-stages: |
      - multiline:
          firstline: '^level.*'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    hostname: zookeeper
    user: root
    expose:
      - "2181"
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
    logging: *norm-logging
    networks:
      - prometheus_dev
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M 

  nimbus:
    image: storm:1.2
    container_name: nimbus
    hostname: nimbus
    user: root
    links:
      - zookeeper
    command: "storm nimbus"
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
    logging: *norm-logging
    networks:
      - prometheus_dev
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M 

  supervisor:
    image: storm:1.2
    #container_name: supervisor
    hostname: supervisor
    user: root
    links:
      - zookeeper
      - nimbus
    command: "storm supervisor"
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
    logging: *norm-logging
    networks:
      - prometheus_dev
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M 

  ui:
    image: storm:1.2
    container_name: ui
    hostname: ui
    user: root
    links:
      - nimbus
    command: "storm ui"
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
    logging: *norm-logging
    networks:
      - prometheus_dev
    ports:
      - "49080:8080"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M 

networks:
  prometheus_dev:
    external: true
