version: '3.7'
services:
  master:
    image: 192.168.136.143:5000/redis:5.0.7
    container_name: redis-master
    restart: always
    command: redis-server --port 6379 --requirepass 123456  --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
 
  slave1:
    image: 192.168.136.143:5000/redis:5.0.7
    container_name: redis-slave-1
    restart: always
    command: redis-server --slaveof redis-master 6379 --port 6380  --requirepass 123456 --masterauth 123456  --appendonly yes
    ports:
      - 6380:6380
    volumes:
      - ./data:/data
 
 
  slave2:
    image: 192.168.136.143:5000/redis:5.0.7
    container_name: redis-slave-2
    restart: always
    command: redis-server --slaveof redis-master 6379 --port 6381  --requirepass 123456 --masterauth 123456 --appendonly yes
    ports:
      - 6381:6381
    volumes:
      - ./data:/data
